In [2]:
import pandas as pd

In [3]:
df=pd.read_csv('eurusd_m1_5years.csv',sep='|')

In [4]:
df.head()

,Date,Time,Pair,Open,High,Low,Close,DAR,WAR,Percent15,...,ANG40_H4,ANG60_H4,ANG120_H4,ANG240_H4,ANG500_H4,ANG1000_H4,MACD_H4,MACD_S_H4,MACD_D_H4,MACD_CV_H4
0,2013.04.08,00:00,EURUSD,1.29732,1.29740,1.29720,1.29727,101.9,256.18,15.0,...,63.90,-28.27,-48.71,-63.60,0.0,0.0,0.41,0.2,0.13,0.69
1,2013.04.08,00:01,EURUSD,1.29728,1.29767,1.29727,1.29753,101.9,256.18,15.0,...,63.95,-28.13,-48.67,-63.60,0.0,0.0,0.41,0.2,0.13,0.69
2,2013.04.08,00:02,EURUSD,1.29754,1.29820,1.29754,1.29814,101.9,256.18,15.0,...,64.07,-27.81,-48.58,-63.57,0.0,0.0,0.41,0.2,0.14,0.69
3,2013.04.08,00:03,EURUSD,1.29815,1.29868,1.29814,1.29863,101.9,256.18,15.0,...,64.17,-27.54,-48.50,-63.56,0.0,0.0,0.42,0.2,0.14,0.69
4,2013.04.08,00:04,EURUSD,1.29867,1.29923,1.29864,1.29902,101.9,256.18,15.0,...,64.24,-27.33,-48.44,-63.55,0.0,0.0,0.42,0.2,0.14,0.69

In [6]:
df.columns[:9]

Index(['Date', 'Time', 'Pair', 'Open', 'High', 'Low', 'Close', 'DAR', 'WAR'], dtype='object')

In [5]:
df.columns[9:25]

Index(['Percent15', 'PercentOpp15', 'CloseDate15', 'CloseTime15', 'Percent25',
       'PercentOpp25', 'CloseDate25', 'CloseTime25', 'Percent35',
       'PercentOpp35', 'CloseDate35', 'CloseTime35', 'Percent50',
       'PercentOpp50', 'CloseDate50', 'CloseTime50'],
      dtype='object')

In [7]:
df.columns[25:50]

Index(['MADIST21_M1', 'MADIST55_M1', 'MADIST144_M1', 'MADIST233_M1',
       'MADIST610_M1', 'RES5_M1', 'SUP5_M1', 'RES9_M1', 'SUP9_M1', 'RES13_M1',
       'SUP13_M1', 'ANG20_M1', 'ANG40_M1', 'ANG60_M1', 'ANG120_M1',
       'ANG240_M1', 'ANG500_M1', 'ANG1000_M1', 'MACD_M1', 'MACD_S_M1',
       'MACD_D_M1', 'MACD_CV_M1', 'MADIST21_M5', 'MADIST55_M5',
       'MADIST144_M5'],
      dtype='object')

In [7]:
df.columns[50:100]

Index(['MADIST233_M5', 'MADIST610_M5', 'RES5_M5', 'SUP5_M5', 'RES9_M5',
       'SUP9_M5', 'RES13_M5', 'SUP13_M5', 'ANG20_M5', 'ANG40_M5', 'ANG60_M5',
       'ANG120_M5', 'ANG240_M5', 'ANG500_M5', 'ANG1000_M5', 'MACD_M5',
       'MACD_S_M5', 'MACD_D_M5', 'MACD_CV_M5', 'MADIST21_M15', 'MADIST55_M15',
       'MADIST144_M15', 'MADIST233_M15', 'MADIST610_M15', 'RES5_M15',
       'SUP5_M15', 'RES9_M15', 'SUP9_M15', 'RES13_M15', 'SUP13_M15',
       'ANG20_M15', 'ANG40_M15', 'ANG60_M15', 'ANG120_M15', 'ANG240_M15',
       'ANG500_M15', 'ANG1000_M15', 'MACD_M15', 'MACD_S_M15', 'MACD_D_M15',
       'MACD_CV_M15', 'MADIST21_M30', 'MADIST55_M30', 'MADIST144_M30',
       'MADIST233_M30', 'MADIST610_M30', 'RES5_M30', 'SUP5_M30', 'RES9_M30',
       'SUP9_M30'],
      dtype='object')

In [8]:
df.columns[100:150]

Index(['RES13_M30', 'SUP13_M30', 'ANG20_M30', 'ANG40_M30', 'ANG60_M30',
       'ANG120_M30', 'ANG240_M30', 'ANG500_M30', 'ANG1000_M30', 'MACD_M30',
       'MACD_S_M30', 'MACD_D_M30', 'MACD_CV_M30', 'MADIST21_H1', 'MADIST55_H1',
       'MADIST144_H1', 'MADIST233_H1', 'MADIST610_H1', 'RES5_H1', 'SUP5_H1',
       'RES9_H1', 'SUP9_H1', 'RES13_H1', 'SUP13_H1', 'ANG20_H1', 'ANG40_H1',
       'ANG60_H1', 'ANG120_H1', 'ANG240_H1', 'ANG500_H1', 'ANG1000_H1',
       'MACD_H1', 'MACD_S_H1', 'MACD_D_H1', 'MACD_CV_H1', 'MADIST21_H4',
       'MADIST55_H4', 'MADIST144_H4', 'MADIST233_H4', 'MADIST610_H4',
       'RES5_H4', 'SUP5_H4', 'RES9_H4', 'SUP9_H4', 'RES13_H4', 'SUP13_H4',
       'ANG20_H4', 'ANG40_H4', 'ANG60_H4', 'ANG120_H4'],
      dtype='object')

In [9]:
df[[ 'PercentOpp15',
        'PercentOpp25',
       'PercentOpp35', 
       'PercentOpp50',]].head(10)

   PercentOpp15  PercentOpp25  PercentOpp35  PercentOpp50
0         -1.64         -1.64         -1.64         -1.64
1         -2.65         -2.65         -2.65         -2.65
2         -5.04         -5.04         -5.04         -5.04
3         -6.95         -6.95         -6.95         -6.95
4         -8.47         -8.47         -8.47         -8.47
5         -8.94         -8.94         -8.94         -8.94
6         -8.31         -8.31         -8.31         -8.31
7         -8.90         -8.90         -8.90         -8.90
8         -7.96         -7.96         -7.96         -7.96
9         -7.96         -7.96         -7.96         -7.96

In [10]:
df15=df['PercentOpp25']

In [11]:
df[df.columns[50:157]].head()

,MADIST233_M5,MADIST610_M5,RES5_M5,SUP5_M5,RES9_M5,SUP9_M5,RES13_M5,SUP13_M5,ANG20_M5,ANG40_M5,...,ANG40_H4,ANG60_H4,ANG120_H4,ANG240_H4,ANG500_H4,ANG1000_H4,MACD_H4,MACD_S_H4,MACD_D_H4,MACD_CV_H4
0,0.10,0.72,127.67,127.55,127.72,127.52,127.72,127.52,-30.59,-22.64,...,63.90,-28.27,-48.71,-63.60,0.0,0.0,0.41,0.2,0.13,0.69
1,0.12,0.75,127.67,127.55,127.72,127.52,127.72,127.52,-30.19,-22.42,...,63.95,-28.13,-48.67,-63.60,0.0,0.0,0.41,0.2,0.13,0.69
2,0.18,0.81,127.67,127.55,127.72,127.52,127.72,127.52,-29.25,-21.88,...,64.07,-27.81,-48.58,-63.57,0.0,0.0,0.41,0.2,0.14,0.69
3,0.23,0.85,127.67,127.55,127.72,127.52,127.72,127.52,-28.48,-21.45,...,64.17,-27.54,-48.50,-63.56,0.0,0.0,0.42,0.2,0.14,0.69
4,0.27,0.89,127.67,127.55,127.72,127.52,127.72,127.52,-27.86,-21.10,...,64.24,-27.33,-48.44,-63.55,0.0,0.0,0.42,0.2,0.14,0.69

In [12]:
df1=pd.DataFrame()
df2=pd.DataFrame()
df3=pd.DataFrame()
df4=pd.DataFrame()
df1=df[df.columns[50:157]]
df2=df[df.columns[50:157]]
df3=df[df.columns[50:157]]
df4=df[df.columns[50:157]]
df1['PercentOpp15']=df['PercentOpp15']
df2['PercentOpp25']=df['PercentOpp25']
df3['PercentOpp35']=df['PercentOpp35']
df4['PercentOpp50']=df['PercentOpp50']

C:\Anaconda\lib\site-packages\ipykernel_launcher.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  if __name__ == '__main__':
C:\Anaconda\lib\site-packages\ipykernel_launcher.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  # Remove the CWD from sys.path while we load stuff.
C:\Anaconda\lib\site-packages\ipykernel_launcher.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  # This is added back by InteractiveShellApp.init_path()
C:\Anaconda\lib\site-packages\ipykernel_launcher.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  if sys.path[0] == '':

# 1 PERCENTAGE 15

In [13]:
df15NoChange=pd.DataFrame()
df15UP=pd.DataFrame()
df15Down=pd.DataFrame()

In [14]:
df15NoChange=df1[df1['PercentOpp15']==0]
df15down=df1[df1['PercentOpp15']<0]
df15up=df1[df1['PercentOpp15']>0]

In [66]:

for column in df15NoChange:
    print( column  ,"---",(df15NoChange[column] == 0).sum()/df15NoChange.shape[0])

MADIST233_M5 --- 0.018061186878
MADIST610_M5 --- 0.00921489126428
RES5_M5 --- 0.0
SUP5_M5 --- 0.0
RES9_M5 --- 0.0
SUP9_M5 --- 0.0
RES13_M5 --- 0.0
SUP13_M5 --- 0.0
ANG20_M5 --- 0.000368595650571
ANG40_M5 --- 0.0
ANG60_M5 --- 0.000368595650571
ANG120_M5 --- 0.000737191301143
ANG240_M5 --- 0.000368595650571
ANG500_M5 --- 0.00147438260229
ANG1000_M5 --- 0.00221157390343
MACD_M5 --- 0.130851455953
MACD_S_M5 --- 0.138223368964
MACD_D_M5 --- 0.259859933653
MACD_CV_M5 --- 0.0
MADIST21_M15 --- 0.0434942867674
MADIST55_M15 --- 0.0302248433468
MADIST144_M15 --- 0.0106892738666
MADIST233_M15 --- 0.007740508662
MADIST610_M15 --- 0.002580169554
RES5_M15 --- 0.0
SUP5_M15 --- 0.0
RES9_M15 --- 0.0
SUP9_M15 --- 0.0
RES13_M15 --- 0.0
SUP13_M15 --- 0.0
ANG20_M15 --- 0.000368595650571
ANG40_M15 --- 0.0
ANG60_M15 --- 0.0
ANG120_M15 --- 0.0
ANG240_M15 --- 0.0
ANG500_M15 --- 0.000368595650571
ANG1000_M15 --- 0.00147438260229
MACD_M15 --- 0.0759307040177
MACD_S_M15 --- 0.0788794692223
MACD_D_M15 --- 0.104312569112
MACD_CV_M15 --- 0.0
MADIST21_M30 --- 0.0324364172503
MADIST55_M30 --- 0.00958348691485
MADIST144_M30 --- 0.007740508662
MADIST233_M30 --- 0.00479174345743
MADIST610_M30 --- 0.00221157390343
RES5_M30 --- 0.0
SUP5_M30 --- 0.0
RES9_M30 --- 0.0
SUP9_M30 --- 0.0
RES13_M30 --- 0.0
SUP13_M30 --- 0.0
ANG20_M30 --- 0.000368595650571
ANG40_M30 --- 0.0
ANG60_M30 --- 0.0
ANG120_M30 --- 0.0
ANG240_M30 --- 0.0
ANG500_M30 --- 0.0
ANG1000_M30 --- 0.000737191301143
MACD_M30 --- 0.0545521562846
MACD_S_M30 --- 0.0497604128271
MACD_D_M30 --- 0.0265388868411
MACD_CV_M30 --- 0.0
MADIST21_H1 --- 0.0121636564689
MADIST55_H1 --- 0.00884629561371
MADIST144_H1 --- 0.005160339108
MADIST233_H1 --- 0.00221157390343
MADIST610_H1 --- 0.00405455215628
RES5_H1 --- 0.0
SUP5_H1 --- 0.0
RES9_H1 --- 0.0
SUP9_H1 --- 0.0
RES13_H1 --- 0.0
SUP13_H1 --- 0.0
ANG20_H1 --- 0.0
ANG40_H1 --- 0.0
ANG60_H1 --- 0.0
ANG120_H1 --- 0.0
ANG240_H1 --- 0.000368595650571
ANG500_H1 --- 0.0
ANG1000_H1 --- 0.0
MACD_H1 --- 0.0239587172871
MACD_S_H1 --- 0.0217471433837
MACD_D_H1 --- 0.00442314780686
MACD_CV_H1 --- 0.0
MADIST21_H4 --- 0.00810910431257
MADIST55_H4 --- 0.00184297825286
MADIST144_H4 --- 0.002580169554
MADIST233_H4 --- 0.00221157390343
MADIST610_H4 --- 0.0
RES5_H4 --- 0.0
SUP5_H4 --- 0.0
RES9_H4 --- 0.0
SUP9_H4 --- 0.0
RES13_H4 --- 0.0
SUP13_H4 --- 0.0
ANG20_H4 --- 0.0
ANG40_H4 --- 0.0
ANG60_H4 --- 0.0
ANG120_H4 --- 0.0
ANG240_H4 --- 0.0
ANG500_H4 --- 0.0165868042757
ANG1000_H4 --- 0.105786951714
MACD_H4 --- 0.01290084777
MACD_S_H4 --- 0.0121636564689
MACD_D_H4 --- 0.0
MACD_CV_H4 --- 0.0
PercentOpp15 --- 1.0

In [64]:


for column in df15down:
    print( column  ,"---",(df15down[column] < 0).sum()/df15down.shape[0])

MADIST233_M5 --- 0.502554978709
MADIST610_M5 --- 0.521750374302
RES5_M5 --- 0.0
SUP5_M5 --- 0.0
RES9_M5 --- 0.0
SUP9_M5 --- 0.0
RES13_M5 --- 0.0
SUP13_M5 --- 0.0
ANG20_M5 --- 0.508660483385
ANG40_M5 --- 0.509869917751
ANG60_M5 --- 0.513056835637
ANG120_M5 --- 0.50676466585
ANG240_M5 --- 0.510873242723
ANG500_M5 --- 0.52481479321
ANG1000_M5 --- 0.533022224815
MACD_M5 --- 0.449730696689
MACD_S_M5 --- 0.446967664158
MACD_D_M5 --- 0.0
MACD_CV_M5 --- 0.508042155204
MADIST21_M15 --- 0.486908164654
MADIST55_M15 --- 0.495879756558
MADIST144_M15 --- 0.511833790274
MADIST233_M15 --- 0.528038655233
MADIST610_M15 --- 0.539355227595
RES5_M15 --- 0.0
SUP5_M15 --- 0.0
RES9_M15 --- 0.0
SUP9_M15 --- 0.0
RES13_M15 --- 0.0
SUP13_M15 --- 0.0
ANG20_M15 --- 0.512504618017
ANG40_M15 --- 0.509115479593
ANG60_M15 --- 0.508845204068
ANG120_M15 --- 0.516296253087
ANG240_M15 --- 0.533288611484
ANG500_M15 --- 0.530756965914
ANG1000_M15 --- 0.555087596492
MACD_M15 --- 0.479939333839
MACD_S_M15 --- 0.478292403119
MACD_D_M15 --- 0.0
MACD_CV_M15 --- 0.512356841471
MADIST21_M30 --- 0.496008088821
MADIST55_M30 --- 0.505932450563
MADIST144_M30 --- 0.530084193743
MADIST233_M30 --- 0.538416068755
MADIST610_M30 --- 0.543117696241
RES5_M30 --- 0.0
SUP5_M30 --- 0.0
RES9_M30 --- 0.0
SUP9_M30 --- 0.0
RES13_M30 --- 0.0
SUP13_M30 --- 0.0
ANG20_M30 --- 0.512247953489
ANG40_M30 --- 0.513480720994
ANG60_M30 --- 0.515166540279
ANG120_M30 --- 0.532781115713
ANG240_M30 --- 0.5236986914
ANG500_M30 --- 0.557735907756
ANG1000_M30 --- 0.571836901359
MACD_M30 --- 0.490812576562
MACD_S_M30 --- 0.492222287036
MACD_D_M30 --- 0.0
MACD_CV_M30 --- 0.510715744035
MADIST21_H1 --- 0.500838048572
MADIST55_H1 --- 0.523706469113
MADIST144_H1 --- 0.540813548776
MADIST233_H1 --- 0.543246028505
MADIST610_H1 --- 0.552762060316
RES5_H1 --- 0.0
SUP5_H1 --- 0.0
RES9_H1 --- 0.0
SUP9_H1 --- 0.0
RES13_H1 --- 0.0
SUP13_H1 --- 0.0
ANG20_H1 --- 0.514777654631
ANG40_H1 --- 0.518452624006
ANG60_H1 --- 0.529384199576
ANG120_H1 --- 0.529660308386
ANG240_H1 --- 0.559715335706
ANG500_H1 --- 0.573386610667
ANG1000_H1 --- 0.547795990589
MACD_H1 --- 0.500978047405
MACD_S_H1 --- 0.500097221412
MACD_D_H1 --- 0.0
MACD_CV_H1 --- 0.513908495207
MADIST21_H4 --- 0.52765560287
MADIST55_H4 --- 0.540710494079
MADIST144_H4 --- 0.548375430205
MADIST233_H4 --- 0.564698905287
MADIST610_H4 --- 0.531101129713
RES5_H4 --- 0.0
SUP5_H4 --- 0.0
RES9_H4 --- 0.0
SUP9_H4 --- 0.0
RES13_H4 --- 0.0
SUP13_H4 --- 0.0
ANG20_H4 --- 0.513474887709
ANG40_H4 --- 0.540885492621
ANG60_H4 --- 0.55489120924
ANG120_H4 --- 0.586970386358
ANG240_H4 --- 0.543613525443
ANG500_H4 --- 0.573409943806
ANG1000_H4 --- 0.530541134379
MACD_H4 --- 0.513712107955
MACD_S_H4 --- 0.512051566237
MACD_D_H4 --- 0.0
MACD_CV_H4 --- 0.516525695619
PercentOpp15 --- 1.0

In [68]:

for column in df15up:
    print( column  ,"---",(df15up[column] >0).sum()/df15up.shape[0])

MADIST233_M5 --- 0.486238929063
MADIST610_M5 --- 0.494915082058
RES5_M5 --- 1.0
SUP5_M5 --- 1.0
RES9_M5 --- 1.0
SUP9_M5 --- 1.0
RES13_M5 --- 1.0
SUP13_M5 --- 1.0
ANG20_M5 --- 0.495182214263
ANG40_M5 --- 0.492582378304
ANG60_M5 --- 0.491115032394
ANG120_M5 --- 0.486432693972
ANG240_M5 --- 0.500417629221
ANG500_M5 --- 0.497945715726
ANG1000_M5 --- 0.464366068943
MACD_M5 --- 0.438804150708
MACD_S_M5 --- 0.434853604027
MACD_D_M5 --- 0.756452559578
MACD_CV_M5 --- 0.496252624292
MADIST21_M15 --- 0.472430827809
MADIST55_M15 --- 0.481007276531
MADIST144_M15 --- 0.494706267448
MADIST233_M15 --- 0.494647949854
MADIST610_M15 --- 0.461662766286
RES5_M15 --- 1.0
SUP5_M15 --- 1.0
RES9_M15 --- 1.0
SUP9_M15 --- 1.0
RES13_M15 --- 1.0
SUP13_M15 --- 1.0
ANG20_M15 --- 0.48857351403
ANG40_M15 --- 0.483797114972
ANG60_M15 --- 0.494326262482
ANG120_M15 --- 0.502359040732
ANG240_M15 --- 0.48230719451
ANG500_M15 --- 0.441509334577
ANG1000_M15 --- 0.442105679005
MACD_M15 --- 0.459898188768
MACD_S_M15 --- 0.456828049634
MACD_D_M15 --- 0.916005733936
MACD_CV_M15 --- 0.488223608467
MADIST21_M30 --- 0.476652269119
MADIST55_M30 --- 0.492567328603
MADIST144_M30 --- 0.489506595532
MADIST233_M30 --- 0.469678613621
MADIST610_M30 --- 0.449194088477
RES5_M30 --- 1.0
SUP5_M30 --- 1.0
RES9_M30 --- 1.0
SUP9_M30 --- 1.0
RES13_M30 --- 1.0
SUP13_M30 --- 1.0
ANG20_M30 --- 0.488637475262
ANG40_M30 --- 0.506729097846
ANG60_M30 --- 0.503036277306
ANG120_M30 --- 0.479101608061
ANG240_M30 --- 0.437538094557
ANG500_M30 --- 0.443226881777
ANG1000_M30 --- 0.426141707991
MACD_M30 --- 0.467197294064
MACD_S_M30 --- 0.468408795046
MACD_D_M30 --- 0.97492155343
MACD_CV_M30 --- 0.487038444463
MADIST21_H1 --- 0.489215007562
MADIST55_H1 --- 0.494463591009
MADIST144_H1 --- 0.461783163899
MADIST233_H1 --- 0.447207527861
MADIST610_H1 --- 0.437082841083
RES5_H1 --- 1.0
SUP5_H1 --- 1.0
RES9_H1 --- 1.0
SUP9_H1 --- 1.0
RES13_H1 --- 1.0
SUP13_H1 --- 1.0
ANG20_H1 --- 0.502840631184
ANG40_H1 --- 0.497806505986
ANG60_H1 --- 0.478428133912
ANG120_H1 --- 0.43854830578
ANG240_H1 --- 0.442073698389
ANG500_H1 --- 0.426879143371
ANG1000_H1 --- 0.438343253595
MACD_H1 --- 0.489690954377
MACD_S_H1 --- 0.493190010008
MACD_D_H1 --- 0.993494766466
MACD_CV_H1 --- 0.503198061598
MADIST21_H4 --- 0.488528364925
MADIST55_H4 --- 0.448451009459
MADIST144_H4 --- 0.444470363375
MADIST233_H4 --- 0.43673293552
MADIST610_H4 --- 0.456671908979
RES5_H4 --- 1.0
SUP5_H4 --- 1.0
RES9_H4 --- 1.0
SUP9_H4 --- 1.0
RES13_H4 --- 1.0
SUP13_H4 --- 1.0
ANG20_H4 --- 0.460076903975
ANG40_H4 --- 0.457823211155
ANG60_H4 --- 0.441930726223
ANG120_H4 --- 0.430000075249
ANG240_H4 --- 0.441488641238
ANG500_H4 --- 0.416225835823
ANG1000_H4 --- 0.331114129412
MACD_H4 --- 0.475152942593
MACD_S_H4 --- 0.464458248365
MACD_D_H4 --- 1.0
MACD_CV_H4 --- 0.469146230426
PercentOpp15 --- 1.0